
CREATE TABLE BANK_1(
BRANCH_ID INT PRIMARY KEY,
BRANCH_NAME VARCHAR(20) NOT NULL,
BRANCH_CITY VARCHAR(20) NOT NULL
);

TRUNCATE TABLE BANK_1;

DROP TABLE BANK_1;


INSERT INTO BANK_1 VALUES(1,'CENTRAL BANK','MUMBAI');
INSERT INTO BANK_1 VALUES(2,'STATE BANK','DELHI');
INSERT INTO BANK_1 VALUES(3,'AXIS BANK','BENGALURU');

SELECT * FROM BANK_1;

DESCRIBE BANK_1;

CREATE  TABLE ACCOUNT_HOLDER(
ACCOUNT_HOLDER_ID varchar(20) PRIMARY KEY,
ACCOUNT_NO INT NOT NULL,
NAME VARCHAR(20) NOT NULL,
CITY VARCHAR(40) NOT NULL,
CONTACT BIGINT, 
DATE_OF_ACCOUNOT DATE NOT NULL,
ACCOUNT_STATUS VARCHAR(30) NOT NULL,
ACCOUNT_TYPE VARCHAR(30) NOT NULL,
BALANCE long NOT NULL
);

TRUNCATE TABLE ACCOUNT_HOLDER;

DROP TABLE ACCOUNT_HOLDER;

INSERT INTO ACCOUNT_HOLDER VALUES('AH001',101,'PRIYA','MUMBAI',9876543210,'2020-01-15', 'ACTIVE','SAVINGS',50000);
INSERT INTO ACCOUNT_HOLDER VALUES('AH002',102,'ROHAN','DELHI',9876543211,'2020-01-20', 'TERMINATED','CURRENT',0);
INSERT INTO ACCOUNT_HOLDER VALUES('AH003',103,'ANANYA','BENGALURU',9876543212,'2020-01-25', 'ACTIVE','SAVINGS',75000);
INSERT INTO ACCOUNT_HOLDER VALUES('AH004',104,'RAHUL','MUMBAI',9876543213,'2020-01-30', 'ACTIVE','CURRENT',125000);

SELECT * FROM ACCOUNT_HOLDER;


CREATE TABLE LOAN(
LOAN_NO INT primary KEY,
BRANCH_ID INT NOT NULL,
ACCOUNT_HOLDER_ID VARCHAR(30) NOT NULL,
LOAN_AMOUNT INT NOT NULL,
LOAN_TYPE VARCHAR(30) NOT NULL

);

TRUNCATE TABLE LOAN;

DROP TABLE LOAN;

INSERT INTO LOAN VALUES(1001,1,'AH001',500000,'HOME LOAN');
INSERT INTO LOAN VALUES(1002,2,'AH002',300000,'PERSONAL LOAN');
INSERT INTO LOAN VALUES(1003,3,'AH003',750000,'CAR LOAN');

SELECT * FROM LOAN;

COMMIT;  


START TRANSACTION; -- Transaction starts here

-- Command 1: Update Priya's balance
UPDATE Account_Holder
SET Balance = Balance - 100 -- Command syntax for update
WHERE Account_Holder_ID = 'AH001';

-- Command 2: Update Rohan's balance
UPDATE Account_Holder
SET Balance = Balance + 100 -- Command syntax for update
WHERE Account_Holder_ID = 'AH002';

COMMIT; -- Save the changes

SELECT * FROM ACCOUNT_HOLDER;

SELECT ACCOUNT_NO,NAME,CITY FROM ACCOUNT_HOLDER WHERE CITY = 'MUMBAI';

 
SELECT ACCOUNT_NO,NAME FROM ACCOUNT_HOLDER WHERE DAY(DATE_OF_ACCOUNOT) >15;

SELECT BRANCH_CITY, COUNT(*) AS COUNT_BRAMCH FROM BANK_1 GROUP BY BRANCH_CITY;


SELECT ACCOUNT_HOLDER.ACCOUNT_HOLDER_ID, ACCOUNT_HOLDER.NAME, LOAN.BRANCH_ID, LOAN.LOAN_AMOUNT
FROM ACCOUNT_HOLDER
RIGHT JOIN LOAN 
ON ACCOUNT_HOLDER.ACCOUNT_HOLDER_ID = LOAN.ACCOUNT_HOLDER_ID;

   

